version: '3.2'

services:
  corretora1:
    image: corretora
    build: ./corretora
    ports:
      - 3001:${PORT:-3333}
    environment:
      - NOME_CORRETORA=${NOME_CORRETORA:-COR1}
      - RMQ_HOST=${RMQ_HOST:-rabbitmq}
      - RMQ_PORT=${RMQ_PORT:-5672}
    volumes:
      - ./corretora:/home/node/app
    depends_on:
      - rabbitmq

  corretora2:
    image: corretora
    build: ./corretora
    ports:
      - 3002:${PORT:-3333}
    environment:
      - NOME_CORRETORA=${NOME_CORRETORA:-COR2}
      - RMQ_HOST=${RMQ_HOST:-rabbitmq}
      - RMQ_PORT=${RMQ_PORT:-5672}
    volumes:
      - ./corretora:/home/node/app
    depends_on:
      - rabbitmq

  bolsa-de-valores:
    image: bolsa-de-valores
    build: ./bolsa-de-valores
    environment:
      - RMQ_HOST=${RMQ_HOST:-rabbitmq}
      - RMQ_PORT=${RMQ_PORT:-5672}
    volumes:
      - ./bolsa-de-valores:/home/node/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    logging:
      driver: none
    container_name: 'rabbitmq'
    ports:
      - ${RMQ_PORT:-5672}:${RMQ_PORT:-5672}
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  rabbitmq-data:
#     name: rmqdata
  rabbitmq-log:
#     name: rmqlog

# networks:
#   default:
#     name: rabbitmq
