version: '3.2'

services:
  api-gateway:
    image: api-gateway
    build: ./api-gateway
    volumes:
      - ./api-gateway:/home/node/app
    ports:
      - '3333:3333'
    depends_on:
      - rabbitmq

  corretora:
    image: corretora
    build: ./corretora
    volumes:
      - ./corretora:/home/node/app
    depends_on:
      - rabbitmq

  bolsa-de-valores:
    image: bolsa-de-valores
    build: ./bolsa-de-valores
    volumes:
      - ./bolsa-de-valores:/home/node/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    logging:
      driver: none
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  rabbitmq-data:
    name: rmqdata
  rabbitmq-log:
    name: rmqlog

networks:
  default:
    name: rabbitmq
