version: '3.2'

services:
  # Cria a corretora 1 COR1 e recebe um amqp url para conectar ao rabbitmq
  corretora1:
    image: corretora
    build: ./corretora
    ports:
      - 3001:${PORT:-3333}
    environment:
      - NOME_CORRETORA=${NOME_CORRETORA:-COR1}
      - AMQP_URL=${AMQP_URL:-amqps://guest:guest@rabbitmq:5672}
    volumes:
      - ./corretora:/home/node/app
    depends_on:
      - rabbitmq

  # Cria a corretora 2 COR2 e recebe um amqp url para conectar ao rabbitmq
  corretora2:
    image: corretora
    build: ./corretora
    ports:
      - 3002:${PORT:-3333}
    environment:
      - NOME_CORRETORA=${NOME_CORRETORA:-COR2}
      - AMQP_URL=${AMQP_URL:-amqps://guest:guest@rabbitmq:5672}
    volumes:
      - ./corretora:/home/node/app
    depends_on:
      - rabbitmq

  #Cria a bolsa de valores e recebe um amqp url para conectar ao rabbitmq
  bolsa-de-valores:
    image: bolsa-de-valores
    build: ./bolsa-de-valores
    environment:
      - AMQP_URL=${AMQP_URL:-amqps://guest:guest@rabbitmq:5672}
    volumes:
      - ./bolsa-de-valores:/home/node/app
    depends_on:
      - rabbitmq

  # Cria o rabbitmq que pode ser acessado pelo dominio 'rabbitmq' dentro dos
  # outros containers

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   logging:
  #     driver: none
  #   container_name: 'rabbitmq'
  #   ports:
  #     - ${RMQ_PORT:-5672}:${RMQ_PORT:-5672}
  #     - 15672:15672
  #   volumes:
  #     - rabbitmq-data:/var/lib/rabbitmq
  #     - rabbitmq-log:/var/log/rabbitmq
# volumes:
# rabbitmq-data:
#     name: rmqdata
# rabbitmq-log:
#     name: rmqlog
